app:
  image: busybox
  volumes:
    - ./src:/var/www/html
  tty: true
  container_name: test-app

fluentd:
  image: fluent/fluentd
  volumes:
    - ./fluentd:/fluentd/etc
  ports:
    - "24224:24224"
  links:
    - elasticsearch:elasticsearch
  container_name: test-fluentd

elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
  container_name: test-elasticsearch

kibana:
  image: kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
  container_name: test-kibana

php-apache:
  image: tuki0918/php-apache
  volumes_from:
    - app
  ports:
    - "80"
    - "443"
  links:
    - fluentd
  log_driver: fluentd
  log_opt:
    fluentd-address: "localhost:24224"
    fluentd-tag: "docker.{{.FullID}}"
  container_name: test-web
